import java.math.BigInteger; // for mathematical operations between big integers
import java.security.MessageDigest; // for one-way hash functions
import java.security.NoSuchAlgorithmException; // for handling exceptions

public class MD5 { 
	public static String getMd5(String input) 
	{ 
		try { 

			// return an object that applies the MD5 algorithm
			MessageDigest md = MessageDigest.getInstance("MD5"); 

			// calculate the hash function and return array of byte 
			byte[] messageDigest = md.digest(input.getBytes()); 

			// convert byte array into signum (signature) representation 
			BigInteger sr = new BigInteger(1, messageDigest); 

			// convert message digest into hexadecimal value 
			String hashtext = sr.toString(16); 
			while (hashtext.length() < 32) { 
				hashtext = "0" + hashtext; 
			} 
			return hashtext; 
		} 

		// exception handling
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	} 

  // return the MD5 hashcode
	public static void main(String args[]) throws NoSuchAlgorithmException 
	{ 
		String s = "JAVA is a good language"; 
		System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s)); 
	} 
}
